name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Build-Test
        run: |
          npm run lint
          npm run format
          npm run build
          NODE_ENV=production npm test
          NODE_ENV=development npm test
